# | Auto Start |
# autostart your favorite applications here
# Keep clipboard content after app closes
exec-once = wl-clip-persist --clipboard regular --reconnect-tries 0 &

# watch idle
exec-once = swayidle -w \
    timeout 300 "~/.config/gtklock/lock.sh" \
    timeout 600 "wlopm --off '*'" \
        resume "wlopm --on '*'" \
    timeout 1800 'systemctl suspend' \
    before-sleep "~/.config/gtklock/lock.sh" \
    after-resume "wlopm --on '*'" &

# bar
exec-once = waybar

#notification daemon
exec-once = swaync &


