99;6u99;6u99;6u# | Auto Start |
# autostart your favorite applications here
# Keep clipboard content after app closes
exec-once = wl-clip-persist --clipboard regular --reconnect-tries 0 &

# watch idle
exec-once = ~/.config/mango/swayidle.sh

# bar
exec-once = waybar

#notification daemon
exec-once = swaync &


