# | Rules |
# Window/Tag/Layer rules. | https://mangowm.github.io/docs/window-management/rules

windowrule = isfloating:1, appid:[Ss]team
windowrule = isfloating:0, title:Steam
windowrule = isfloating:1, appid:steam, title:Steam Settings

layerrule = noanim:1, noblur:1, layer_name:selection

windowrule=isfloating:1,isoverlay:1,width:760,height:800,offsetx:95,offsety:-90,appid:^nmtui$ ## This makes nm-tui open next to network module in waybar
windowrule=isfloating:1,isoverlay:1,width:760,height:800,offsetx:95,offsety:-90,appid:^blueman-manager$ ## This makes blueman open next to bluetooth module in waybar
