[files]
current_page=8
FILE_NAME_0=123;None;0;EUTF-8;1;1;0;%2Fhome%2Fmangorator%2FRampant-Mango%2Feww%2F.config%2Feww%2Feww.yuck;0;4
FILE_NAME_1=65;Sh;0;EUTF-8;1;1;0;%2Fhome%2Fmangorator%2FRampant-Mango%2Feww%2F.config%2Feww%2Fscripts%2Fdu.sh;0;4
FILE_NAME_2=70;Sh;0;EUTF-8;1;1;0;%2Fhome%2Fmangorator%2FRampant-Mango%2Feww%2F.config%2Feww%2Fscripts%2Fproton-status.sh;0;4
FILE_NAME_3=0;Sh;0;EUTF-8;1;1;0;%2Fhome%2Fmangorator%2FRampant-Mango%2Feww%2F.config%2Feww%2Fscripts%2Fgetvol;0;4
FILE_NAME_4=235;CSS;0;EUTF-8;1;1;0;%2Fhome%2Fmangorator%2FRampant-Mango%2Feww%2F.config%2Feww%2Feww.css;0;4
FILE_NAME_5=2013;Sh;0;EUTF-8;1;1;0;%2Fhome%2Fmangorator%2FRampant-Mango%2Fscripts%2Finstall.sh;0;4
FILE_NAME_6=53;Sh;0;EUTF-8;1;1;0;%2Fhome%2Fmangorator%2FRampant-Mango%2Feww%2F.config%2Feww%2Fscripts%2Fram-use.sh;0;4
FILE_NAME_7=28;Sh;0;EUTF-8;1;1;0;%2Fhome%2Fmangorator%2FRampant-Mango%2Feww%2F.config%2Feww%2Fscripts%2Fhost-name.sh;0;4
FILE_NAME_8=951;CSS;0;EUTF-8;1;1;0;%2Fhome%2Fmangorator%2FRampant-Mango%2Fgtklock%2F.config%2Fgtklock%2Fnostrolock.css;0;4
FILE_NAME_9=0;Sh;0;EUTF-8;1;1;0;%2Fhome%2Fmangorator%2FRampant-Mango%2Fgtklock%2F.config%2Fgtklock%2Flock.sh;0;4
FILE_NAME_10=1171;XML;0;EUTF-8;1;1;0;%2Fhome%2Fmangorator%2FRampant-Mango%2Fgtklock%2F.config%2Fgtklock%2Flayout.xml;0;4
