[files]
current_page=2
FILE_NAME_0=117;None;0;EUTF-8;1;1;0;%2Fhome%2Fmangorator%2FRampant-Mango%2Feww%2F.config%2Feww%2Feww.yuck;0;4
FILE_NAME_1=0;Sh;0;EUTF-8;1;1;0;%2Fhome%2Fmangorator%2FRampant-Mango%2Feww%2F.config%2Feww%2Fscripts%2Fdu.sh;0;4
FILE_NAME_2=0;Sh;0;EUTF-8;1;1;0;%2Fhome%2Fmangorator%2FRampant-Mango%2Feww%2F.config%2Feww%2Fscripts%2Fproton-status.sh;0;4
