# Noctalia Theme for Mango
# Generated automatically by Noctalia

rootcolor = 0x080b09ff
bordercolor = 0x576057ff
dropcolor = 0xff9c0080
splitcolor = 0x080b09ff
focuscolor = 0xff9c00ff
maximizescreencolor = 0x9b5f00ff
urgentcolor = 0xff4b00ff
scratchpadcolor = 0x080b09ff
globalcolor = 0x4d2f00ff
overlaycolor = 0x4d2f00ff
jump_label_decorate_fg_color = 0xf2ae00ff
jump_label_decorate_bg_color = 0x202722ff
jump_label_decorate_focus_fg_color = 0x2e2100ff
jump_label_decorate_focus_bg_color = 0xff9c00ff
jump_label_decorate_border_color = 0x576057ff
group_bar_decorate_fg_color = 0xf2ae00ff
group_bar_decorate_bg_color = 0x202722ff
group_bar_decorate_focus_fg_color = 0x2e2100ff
group_bar_decorate_focus_bg_color = 0xff9c00ff
group_bar_decorate_border_color = 0x576057ff
