"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](bg:color_primary fg:color_surface)\
$hostname\
[](bg:color_secondary fg:color_primary)\
$directory\
[](fg:color_secondary bg:color_primary)\
$git_branch\
[](fg:color_primary bg:color_secondary)\
$time\
[](fg:color_secondary bg:color_surface)\
$line_break$character"""

palette = 'bughunt_dark'

[palettes.bughunt_dark]
color_primary = '#756000'
color_surface = '#1d170b'
color_secondary = '#3b3000'
color_alert = '#752300'
color_superior = '#9c8000'
color_green = '#007500'
color_text = '#d6c98f'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

# ~/.config/starship.toml

[hostname]
ssh_only = false
format = "[$hostname](fg:color_surface bg:color_primary)"
disabled = false

[username]
show_always = false
style_user = "bg:color_primary fg:color_surface"
style_root = "bg:color_alert fg:color_surface"
format = '[ $user ]($style)'

[directory]
style = "bg:color_secondary fg:color_superior"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = "git"
style = "bg:color_primary"
format = '[[ $symbol ](fg:color_surface bg:color_primary)]($style)'


[time]
disabled = false
time_format = "%R"
style = "bg:color_bg1"
format = '[[$time](fg:color_superior bg:color_secondary)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[>>](bold fg:color_primary)'
error_symbol = '[>>](bold fg:color_alert)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'
