[colors.primary]
background = '#ffffff'
foreground = '#d8e1dc'

[colors.cursor]
text = '#080b09'
cursor = '#00d39e'

[colors.vi_mode_cursor]
text = '#080b09'
cursor = '#ff9c00'

[colors.search.matches]
foreground = '#171c18'
background = '#080b09'

[colors.search.focused_match]
foreground = '#171c18'
background = '#ff9c00'

[colors.footer_bar]
foreground = '#171c18'
background = '#e3e8e5'

[colors.hints.start]
foreground = '#171c18'
background = '#9b5f00'

[colors.hints.end]
foreground = '#171c18'
background = '#9b5f00'

[colors.selection]
text = '#f0f4f2'
background = '#006e53'


[colors.normal]
black   = '#171c18'
red     = '#ff5c57'
green   = '#4fd6a2'
yellow  = '#f2ae00'
blue    = '#62a8ff'
magenta = '#c792ea'
cyan    = '#42d9d0'
white   = '#c8d0cc'


[colors.bright]
black   = '#56615b'
red     = '#ff7b72'
green   = '#79e6b9'
yellow  = '#ffd166'
blue    = '#89bcff'
magenta = '#dda8f5'
cyan    = '#72eee6'
white   = '#f0f4f2'


[colors.dim]
black   = '#171c18'
red     = '#ff5c57'
green   = '#4fd6a2'
yellow  = '#f2ae00'
blue    = '#62a8ff'
magenta = '#c792ea'
cyan    = '#42d9d0'
white   = '#c8d0cc'
