#!/usr/bin/env bash

choice=$(printf '%s\n' \
    "Bluetooth" \
    "Power" \
    "Screenshots" |
    fuzzel --dmenu \
        --prompt="> " \
        --lines=8 \
        --width=20)

case "$choice" in
    "Bluetooth")
        "$HOME/.local/share/bin/bluetooth-menu"
        ;;
    "Power")
        "$HOME/.local/share/bin/power-menu"
        ;;
    "Screenshots")
        "$HOME/.local/share/bin/screenshot-menu"
        ;;
esac
