[theme]
mode = "dark"
source = "custom"
custom_palette = "muthur"

[bar.default]
background_opacity = 0.9
start = [ "Spacer", "workspaces" ]
center = [ "Spacer_2", "clock", "Spacer_2" ]
end = [
    "tray",
    "Spacer_2",
    "notifications",
    "clipboard",
    "Spacer_2",
    "network",
    "bluetooth",
    "volume",
    "battery",
    "Spacer_2",
    "date",
    "Spacer_2",
    "session",
    "Spacer"
]
margin_edge = 0
margin_ends = 0
radius_bottom_left = 20
radius_bottom_right = 20
radius_top_left = 0
radius_top_right = 0
thickness = 40

[wallpaper.default]
path = "/usr/share/wallpapers/cachyos-wallpapers/cachysurf4.jpg"

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]

    [idle.behavior.Screen-off]
    action = "command"
    enabled = true
    timeout = 60.0

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 120.0

    [idle.behavior.lock-and-suspend]
    action = "suspend"
    enabled = true
    lock_before_suspend = true
    timeout = 900.0

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@DP-2", "lockscreen-login-box@DP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-1"]
    box_height = 70.0
    box_width = 200.0
    cx = 1280.0
    cy = 1321.0
    output = "DP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-1".settings]
        color = "primary"
        background_color = "surface_variant"
        background_opacity = 0.5
        background_radius = 12.0
        input_opacity = 1.0
        input_radius = 16.0
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_password_hint = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-2"]
	color="primary"
    box_height = 70.0
    box_width = 200.0
    cx = 1280.0
    cy = 1321.0
    output = "DP-2"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-2".settings]
        background_color = "surface_variant"
        background_opacity = 0.2
        background_radius = 12.0
        input_opacity = 1.0
        input_radius = 6.0
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_password_hint = true

[plugin_settings."noctalia/screen_recorder"]
restore_portal = false

[plugins]
enabled = [ "noctalia/screen_recorder", "dotnetrob/cat", "noctalia/wallhaven" ]

    [[plugins.source]]
    kind = "git"
    location = "https://github.com/noctalia-dev/official-plugins"
    name = "official"

    [[plugins.source]]
    kind = "git"
    location = "https://github.com/noctalia-dev/community-plugins"
    name = "community"

[shell]
polkit_agent = true
settings_show_advanced = true

#[theme]
#builtin = "Noctalia"
#mode = "dark"
#source = "wallpaper"

#    [theme.templates]
#    builtin_ids = [ "gtk3", "gtk4", "kcolorscheme", "qt" ]

[widget.Spacer]
length = 10
type = "spacer"

[widget.Spacer_2]
type = "spacer"

[widget.cat]
cat_size = 34
type = "dotnetrob/cat:cat"

[widget.clock]
color = "primary"
scale = 2
format= "{:%H / %M}"
capsule=true
capsule_padding=30
capsule_border= "Primary"
capsule_radius = 5

[widget.date]
color = "primary"
format = "{:%d / %m}"
scale = 2

[widget.launcher]
custom_image = "/usr/share/icons/hicolor/scalable/apps/org.cachyos.hello.svg"
scale = 1.45

[widget.network]
show_label = false
scale=2
color="primary"

[widget.recorder]
type = "noctalia/screen_recorder:recorder"
scale=1.5
color="primary"

[widget.tray]
scale=1.5
capsule=true
capsule_border= "Primary"
capsule_radius = 5

[widget.notifications]
scale=1.5
color="primary"

[widget.clipboard]
scale=1.5
color="primary"

[widget.bluetooth]
scale=1.5
color="primary"

[widget.volume]
scale=1.5
color="primary"
capsule=true
capsule_border= "Primary"
capsule_radius = 5

[widget.battery]
scale=1.5
color="primary"
capsule=true
capsule_border= "Primary"
capsule_radius = 5

[widget.session]
scale=1.5
color="primary"

[widget.workspaces]
scale=2
style = "regular"
show_labels= true
capsule_radius = 5
active_pill_size=1
inactive_pill_size=1
capsule_border = "Primary"
anchor = true
display = "name"
focused_color= "Primary"
occupied_color="Secondary"
empty_color="surface"
urgent_color="Error"
