#!/usr/bin/env python3
"""Generate the small Bughunt icon overlay from colors.css. No third-party assets."""
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
THEME = ROOT / 'gtk/.local/share/icons/Bughunt'
palette = dict(re.findall(r'@define-color\s+(\w+)\s+([^;]+);',
                          (ROOT / 'colors/.config/colors/colors.css').read_text()))


def color(name):
    value = palette[name].strip()
    if value.startswith('@'):
        return color(value[1:])
    if not re.fullmatch(r'#[0-9a-fA-F]{6}', value):
        raise ValueError(f'{name}: icons require a hex color or a named-color alias')
    return value


bg, muted, fill, edge, ink = map(color, ('surface', 'secondary', 'primary', 'gtk_accent', 'text'))


def svg(body):
    return (f'<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" viewBox="0 0 64 64">\n'
            f'  <!-- Generated by scripts/build-gtk-icons.py; edit colors.css and regenerate. -->\n'
            f'  <g stroke-linejoin="miter" stroke-linecap="square">{body}</g>\n</svg>\n')


def glyph(path, stroke=ink):
    return f'<path d="{path}" fill="none" stroke="{stroke}" stroke-width="3"/>'


def folder(mark=''):
    return svg(f'<path d="M5 13H25L31 20H59V56H5Z" fill="{muted}" stroke="{edge}" stroke-width="2"/>'
               f'<path d="M5 26H59V56H5Z" fill="{fill}" stroke="{edge}" stroke-width="2"/>'
               f'<path d="M9 30H21" stroke="{ink}" stroke-width="2"/>{mark}')


folders = {
    'folder': '',
    'folder-open': 'M22 41H42 M36 35L42 41L36 47',
    'folder-documents': 'M26 33H39V50H26Z M29 38H36 M29 43H36',
    'folder-download': 'M32 33V45 M26 40L32 46L38 40 M24 50H40',
    'folder-music': 'M29 46V35L40 33V44 M24 46H29V50H24Z M35 44H40V48H35Z',
    'folder-pictures': 'M23 34H42V49H23Z M23 46L29 40L35 46L39 42L42 45',
    'folder-videos': 'M24 34H42V50H24Z M29 34V50 M37 34V50 M24 39H29 M37 39H42 M24 45H29 M37 45H42',
    'folder-templates': 'M25 34H40V49H25Z M30 38H40 M30 42H40 M30 46H40',
    'folder-publicshare': 'M25 36H39V46H25Z M32 46V51 M24 51H40',
    'folder-remote': 'M23 34H31V42H23Z M36 43H44V51H36Z M31 38H40V43',
    'folder-saved-search': 'M25 33H36V44H25Z M36 44L42 50',
}
for name, mark in folders.items():
    path = THEME / 'scalable/places' / f'{name}.svg'
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(folder(glyph(mark) if mark else ''))

shapes = {
    'places/user-home': f'<path d="M6 29L32 8L58 29V56H6Z" fill="{muted}" stroke="{edge}" stroke-width="3"/>' + glyph('M15 30V49H26V36H38V49H49V30'),
    'places/user-desktop': f'<path d="M6 10H58V46H6Z" fill="{muted}" stroke="{edge}" stroke-width="3"/>' + glyph('M12 16H52V37H12Z M32 46V54 M20 55H44'),
    'places/user-trash': f'<path d="M16 20H48V56H16Z" fill="{muted}" stroke="{edge}" stroke-width="3"/>' + glyph('M12 16H52 M24 16V10H40V16 M25 27V47 M39 27V47'),
    'places/network-workgroup': glyph('M24 6H40V22H24Z M7 42H23V58H7Z M41 42H57V58H41Z M32 22V32 M15 42V32H49V42', edge),
    'devices/computer': f'<path d="M6 9H58V43H6Z" fill="{muted}" stroke="{edge}" stroke-width="3"/>' + glyph('M12 15H52V36H12Z M32 43V52 M19 54H45 M15 24L20 28L15 32 M27 32H36'),
    'devices/drive-harddisk': f'<path d="M16 10H48L57 40V55H7V40Z" fill="{muted}" stroke="{edge}" stroke-width="3"/>' + glyph('M7 40H57 M16 47H22 M44 47H48'),
    'mimetypes/text-x-generic': f'<path d="M13 6H39L51 18V58H13Z" fill="{bg}" stroke="{edge}" stroke-width="3"/>' + glyph('M39 6V19H51 M21 29H42 M21 37H42 M21 45H35'),
}
for name, body in shapes.items():
    path = THEME / 'scalable' / f'{name}.svg'
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(svg(body))

# Synonyms use symlinks so folder artwork has one source per variant.
aliases = {
    'places/inode-directory': 'folder',
    'places/folder-drag-accept': 'folder-open',
    'places/user-trash-full': 'user-trash',
    'places/network-server': 'network-workgroup',
    'devices/drive-harddisk-system': 'drive-harddisk',
    'devices/drive-harddisk-root': 'drive-harddisk',
    'devices/drive-removable-media': 'drive-harddisk',
    'devices/drive-harddisk-usb': 'drive-harddisk',
    'devices/drive-removable-media-usb': 'drive-harddisk',
    'mimetypes/text-plain': 'text-x-generic',
    'mimetypes/application-x-generic': 'text-x-generic',
}
for name, target in aliases.items():
    path = THEME / 'scalable' / f'{name}.svg'
    if path.is_symlink():
        path.unlink()
    elif path.exists():
        raise FileExistsError(f'Refusing to replace non-symlink: {path}')
    path.symlink_to(f'{target}.svg')

contexts = {'places': 'Places', 'devices': 'Devices', 'mimetypes': 'MimeTypes'}
index = ('[Icon Theme]\nName=Bughunt\nComment=Angular amber navigation icons\n'
         'Inherits=Adwaita,hicolor\nExample=folder\n'
         'Directories=' + ','.join('scalable/' + c for c in contexts) + '\n')
for directory, context in contexts.items():
    index += (f'\n[scalable/{directory}]\nSize=64\nMinSize=16\nMaxSize=512\n'
              f'Type=Scalable\nContext={context}\n')
(THEME / 'index.theme').write_text(index)
print(f'Generated {len(folders) + len(shapes)} SVGs and {len(aliases)} aliases in {THEME}')
