[Icon Theme]
Name=Muthur
Comment=Angular amber navigation icons
Inherits=Adwaita,hicolor
Example=folder
Directories=scalable/places,scalable/devices,scalable/mimetypes

[scalable/places]
Size=64
MinSize=16
MaxSize=512
Type=Scalable
Context=Places

[scalable/devices]
Size=64
MinSize=16
MaxSize=512
Type=Scalable
Context=Devices

[scalable/mimetypes]
Size=64
MinSize=16
MaxSize=512
Type=Scalable
Context=MimeTypes
