# ═══════════════════════════════════════════════════════
# BUGHUNT / KITTY
# ═══════════════════════════════════════════════════════

# Font
font_family             Terminus (TTF)
bold_font               Terminus (TTF)
italic_font             auto
bold_italic_font        auto
font_size               20.0

# Window
window_padding_width    8
confirm_os_window_close 0

# Base colors
background              #1d170b
foreground              #c7bd94

# Cursor
cursor                  #9c8000
cursor_text_color       #1d170b
cursor_shape            block
cursor_blink_interval   0.5

# Selection
selection_background    #3b3000
selection_foreground    #ddd3a8

# ANSI normal
color0                  #1d170b
color1                  #a63c2d
color2                  #71935a
color3                  #9c8000
color4                  #527f8f
color5                  #8b6577
color6                  #57958d
color7                  #b8ae89

# ANSI bright
color8                  #665d45
color9                  #d05a43
color10                 #9dbb72
color11                 #c5a629
color12                 #78a9b7
color13                 #b88ba0
color14                 #7dbdb2
color15                 #e1d8b4
