# terminal base
background #1d170b
foreground #c7bd94

# ANSI normal
color0  #c7bd94   # "black" -> used as text on nmtui panels
color1  #756000   # selected-row background
color2  #71935a
color3  #9c8000
color4  #3b3000
color5  #8b6577
color6  #57958d
color7  #1d170b   # nmtui panel/background

# ANSI bright
color8  #665d45
color9  #9c8000
color10 #9dbb72
color11 #c5a629
color12 #756000
color13 #b88ba0
color14 #7dbdb2
color15 #ddd3a8
